# Generated by Django 5.0.7 on 2024-10-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_shopuser_email'),
    ]

    operations = [
    ]
